@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk0MTQxODJ9.hciCYbxceZsLW2cmC0Dhas5JgvyXFDxa3nM3Qn2tyX4

### user create
POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "test3_first",
  "last_name": "test3_last",
  "email": "test3@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### session create
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "password"
}

### trip create
POST http://localhost:3000/trips
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "resort_id": 40,
  "day_start": "12/14/22",
  "day_end": "01/03/23",
  "original_query": "test"
}